openapi: 3.0.3
info:
  title: MCP Server API
  description: Model Context Protocol Server for text processing
  version: 1.0.0
servers:
  - url: http://localhost:8000
security:
  - ApiKeyAuth: []
paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  timestamp:
                    type: string
  /v1/summarize:
    post:
      summary: Summarize text
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [requestId, text]
              properties:
                requestId:
                  type: string
                  format: uuid
                text:
                  type: string
                  maxLength: 10485760
                options:
                  type: object
                  properties:
                    maxSentences:
                      type: integer
                      default: 3
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  tool:
                    type: string
                  durationMs:
                    type: integer
                  result:
                    type: object
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
